### ISSUE TITLE
Default block_device_mapping fields

### ISSUE THREAD

**Issue by tyler-ball** [test-kitchen/kitchen-ec2#118]
Currently if you want to overwrite the `block_device_mappings`, you are required to specify all 3 fields:

```yaml
block_device_mappings:
  - ebs_device_name: /dev/sda1
    ebs_volume_size: 8
    ebs_delete_on_termination: true
```

We should default `ebs_volume_size` and `ebs_delete_on_termination` if they are not provided, so the following config would work:

```yaml
block_device_mappings:
  - ebs_device_name: /dev/sda1
    # ebs_volume_size will be defaulted to 8
    # ebs_delete_on_termination will be defaulted to true
```
