### ISSUE TITLE
hostname missing when waiting for ssh service in create action 

### ISSUE THREAD

**Issue by litjoco** [test-kitchen/kitchen-ec2#122]
During the `create` action the instance is created and logged as `ready`.  Following this the ssh connection is being checked.  The connection is always fails made and eventually times out. I am able to manually connect during this time using same keypair.  From the log it looks like the hostname is not getting set.  

I have tried explicitly setting the `interface_type` and leaving it as default with same result.

```
       Waiting for SSH service on :22, retrying in 3 seconds
D      [SSH] opening connection to ec2-user@<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>"zlib", :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>120, :keys_only=>true, :keys=>["/some/path/key.pem"], :user=>"ec2-user"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "" port 22>)
```

fyi: After the time out the state file is created with the instance id but hostname is empty

**Comment by dsavinkov** [comment]
@litjoco 
Make sure to adjust your `.kitchen.yml` file:
```yml
...
platforms:
  - name: centos-6.3
    driver_plugin: ec2
    transport:
      username: test
      ssh_key: <%= ENV['AWS_SSH_KEY']%>
...
```
It works correctly for me.
