### ISSUE TITLE
TK Can't Connect to EC2 Instance via SSH

### ISSUE THREAD

**Issue by jcderose** [test-kitchen/kitchen-ec2#135]
In the process of creating an EC2 instance via TK, TK gets stuck attempting to SSH into the instance.

```
➜ kitchen create
-----> Starting Kitchen (v1.4.0)
-----> Creating <default-amazon>...
       Creating <>...
If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

       Instance <i-de580128> requested.
       EC2 instance <i-de580128> created.
       Waited 0/300s for instance <i-de580128> to become ready.
       Waited 5/300s for instance <i-de580128> to become ready.
       Waited 10/300s for instance <i-de580128> to become ready.
       Waited 15/300s for instance <i-de580128> to become ready.
       Waited 20/300s for instance <i-de580128> to become ready.
       EC2 instance <i-de580128> ready.
       Waiting for SSH service on ec2-52-25-230-10.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-52-25-230-10.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-52-25-230-10.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
```

This "Waiting" message continues endlessly until I quit the process (and then TK barks that the instance wasn't created successfully, even though it's up and running in AWS). While TK is attempting to SSH in during the `kitchen create` process, I'm able to SSH into the instance manually so I know the instance is accepting SSH connections correctly.

I'm running the latest version of TK and the kitchen-ec2 driver.
```
➜ chef gem list | grep kitchen
kitchen-ec2 (0.9.2)
test-kitchen (1.4.0)
```

Here's my `.kitchen.yml` file.
```
---
driver:
  name: ec2
  security_group_ids: ["sg-5d213838"]
  region: us-west-2
  availability_zone: us-west-2a
  require_chef_omnibus: true
  subnet_id: subnet-eb8f489c
  image_id: "ami-ff527ecf"
  associate_public_ip: true

transport:
  username: ec2-user

provisioner:
  name: chef_solo

platforms:
  - name: amazon

suites:
  - name: default
    run_list:
    attributes:
```

Here's my environment variables (for the SSH connection, set in my login script):
```
export AWS_ACCESS_KEY_ID="XXXXXXXX"
export AWS_SECRET_ACCESS_KEY="XXXXXXXX"
export AWS_SSH_KEY_ID="key1"
export AWS_SSH_KEY="$HOME/.ssh/$AWS_SSH_KEY_ID.pem"
```
