### ISSUE TITLE
ebs_volume_type missing parameters when set to 'io1'

### ISSUE THREAD

**Issue by gmiranda23** [test-kitchen/kitchen-ec2#157]
Using the following block_device mappings produces an error:

```yaml
block_device_mappings:
  - ebs_device_name: /dev/sdb
    ebs_volume_type: io1
    ebs_virtual_name: test
    ebs_volume_size: 8
    ebs_delete_on_termination: true
```

```
$ bundle exec kitchen setup
-----> Starting Kitchen (v1.4.1.dev)
-----> Creating <default-centos-7>...
       Creating <>...

\>>>>>> ------Exception-------
\>>>>>> Class: Kitchen::ActionFailed
\>>>>>> Message: Failed to complete #create action: [The parameter iops must be specified for io1 volumes.]
\>>>>>> ----------------------
\>>>>>> Please see .kitchen/logs/kitchen.log for more details
\>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I'm unable to find how that parameter should be set.
