### ISSUE TITLE
busser bats tests don't run

### ISSUE THREAD

**Issue by joegoggins** [test-kitchen/kitchen-ec2#16]
When I run `kitchen test`, my .bats files don't run.

My integration test directory is like

```
▾ test/
  ▾ integration/
    ▾ default/
      ▾ bats/
          verify_installed_packages.bats
```

My .kitchen.yml is like this:

```

---
driver_plugin: ec2
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.4
  driver_config:
...
    region: us-east-1
    availability_zone: us-east-1b
    flavor_id: t1.micro
    # username: root
    require_chef_omnibus: true
    groups: ssh-only

suites:
- name: default
  run_list: ["recipe[spark-base]"]
  attributes: {}
```

This is for test-kitchen (~> 1.0.0.beta.3)

Any ideas of why this might happen?
