### ISSUE TITLE
Specify block_device_mappings as desired by AWS

### ISSUE THREAD

**Issue by tyler-ball** [test-kitchen/kitchen-ec2#164]
It is weird that we have a flat list of block_device_mappings when we could just have users specify the hash desired by http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#create_image-instance_method - lets update to that on the next compatability update

**Comment by midnightconman** [comment]
Will this be added pre 1.0, or could we maybe have a patch?

**Comment by tyler-ball** [comment]
@midnightconman This will be added for the 1.0.0 release.  But most of the functionality should already be available via https://github.com/test-kitchen/kitchen-ec2#disk-configuration - is there something missing there that you need?

**Comment by midnightconman** [comment]
I'm looking for ephemeral storage support, like @atward

**Comment by tyler-ball** [comment]
@midnightconman Unfortunately I'm swamped right now.  Would you want to take a stab at a PR?

**Comment by bennyscetbun** [comment]
```  
block_device_mappings:
  - ebs_virtual_name: ephemeral0
    ebs_device_name: /dev/xvdba
    ebs_volume_size: null
    ebs_delete_on_termination: null
  - ebs_virtual_name: ephemeral1
    ebs_device_name: /dev/xvdbb
    ebs_volume_size: null
    ebs_delete_on_termination: null
```

this is a workaround :) (you can of course change xvdba and xvdbb to what you want
