### ISSUE TITLE
Support empheral storage

### ISSUE THREAD

**Issue by atward** [test-kitchen/kitchen-ec2#172]
I currently can't see a way to attach ephemeral drives. 

Using the following config, which is valid for cloudformation and block_device_mappings in the aws ruby sdk:

```
driver:
  name: ec2
  instance_type: m3.large
  block_device_mappings:
    - ebs_device_name: /dev/sdb
      ebs_virtual_name: ephemeral0
```

Produces error:

```
$ kitchen list
/Users/adamward/.chefdk/gem/ruby/2.1.0/gems/kitchen-ec2-0.9.5/lib/kitchen/driver/ec2.rb:117:in `block (2 levels) in <class:Ec2>': Every :block_device_mapping must include the keys :ebs_volume_size, :ebs_delete_on_termination and :ebs_device_name (RuntimeError)
```

Relates to #164 - as being able to provide the direct hash should solve this issue.
