### ISSUE TITLE
AWS credentials definition deprecated?

### ISSUE THREAD

**Issue by alamut** [test-kitchen/kitchen-ec2#180]
I'm getting these messages after `kitchen-ec2` upgrade to the latest version:

```
$$$$$$ WARN: aws_access_key_id has been deprecated, please use ENV['AWS_ACCESS_KEY_ID'] or ~/.aws/credentials.  See the README for more details
$$$$$$ WARN: aws_secret_access_key has been deprecated, please use ENV['AWS_SECRET_ACCESS_KEY'] or ~/.aws/credentials.  See the README for more details
```

My config looks like:

```

---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
```

For sure I have my valid credentials set by `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env vars. I tried to remove these keys from the config, but then I'm getting this message, most probably thrown by the `aws-sdk`:

```
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #destroy action: [unable to sign request without credentials set]
```

So what's the problem with my config and why it is no longer cool?
I don't want to write any files in like `~/.aws/credentials` since I have dozens of projects with different creds and I'm switching them dozens time per day.

Am I missing something? Should I apply some magic to my config?
The README seems a bit messy about that.

Thanks in advance.
