### ISSUE TITLE
'username' config is not consistent across OS platforms

### ISSUE THREAD

**Issue by scarolan** [test-kitchen/kitchen-ec2#182]
With Linux you have to do it like this for it to work, even though it throws a warning.  I tried putting username under the 'transport' but it fails.

```
suites:
  - name: linux
    driver_config:
      image_id: ami-a9de9c99
      username: root
      transport:
        ssh_key: C:\Users\Administrator\.ssh\gramsay.pem
    run_list:
      #- recipe[motd::default]
    attributes:
```

With Windows you put everything under 'transport' instead:

```
 - name: windows
    driver_config:
      image_id: ami-c3b3b1f3
      transport:
        username: chef
```

Can we make the behavior the same for both platforms?
