### ISSUE TITLE
undefined method `wait_until_exists' for #<Aws::EC2::Instance id="***">

### ISSUE THREAD

**Issue by puneetloya** [test-kitchen/kitchen-ec2#233]
I am trying to start an instance from an amazon ami using Kitchen-ec2.

I am getting an error at this line:

https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/ec2.rb#L170

So I debugged into the gem:

Stopping on the above line, below is the output of 
**server.methods**:

[:id, :attach_volume, :console_output, :create_image, :create_tags, :describe_attribute, :detach_volume, :modify_attribute, :monitor, :password_data, :reboot, :report_status, :reset_attribute, :reset_kernel, :reset_ramdisk, :reset_source_dest_check, :start, :stop, :terminate, :unmonitor, __:wait_until_running__, __:wait_until_stopped__, __:wait_until_terminated__, :image, :key_pair, :placement_group, :subnet, :vpc, :volumes, :instance_id, :image_id, :state, :private_dns_name, :public_dns_name, :state_transition_reason, :key_name, :ami_launch_index, :product_codes, :instance_type, :launch_time, :placement, :kernel_id, :ramdisk_id, :platform, :monitoring, :subnet_id, :vpc_id, :private_ip_address, :public_ip_address, :state_reason, :architecture, :root_device_type, :root_device_name, :block_device_mappings, :virtualization_type, :instance_lifecycle, :spot_instance_request_id, :client_token, :tags, :security_groups, :source_dest_check, :hypervisor, :network_interfaces, :iam_instance_profile, :ebs_optimized, :sriov_net_support, :decrypt_windows_password, :client, :identifiers, :data, :data_loaded?, :load, :reload, :inspect, :psych_to_yaml, :to_yaml, :to_yaml_properties, :blank?, :present?, :presence, :try, :try!, :dclone, :to_json, :nil?, :===, :=~, :!~, :eql?, :hash, :<=>, :class, :singleton_class, :clone, :dup, :itself, :taint, :tainted?, :untaint, :untrust, :untrusted?, :trust, :freeze, :frozen?, :to_s, :methods, :singleton_methods, :protected_methods, :private_methods, :public_methods, :instance_variables, :instance_variable_get, :instance_variable_set, :instance_variable_defined?, :remove_instance_variable, :instance_of?, :kind_of?, :is_a?, :tap, :send, :public_send, :respond_to?, :extend, :display, :method, :public_method, :singleton_method, :define_singleton_method, :object_id, :to_enum, :enum_for, :gem, :byebug, :debugger, :silence_warnings, :enable_warnings, :with_warnings, :silence_stderr, :silence_stream, :suppress, :capture, :silence, :quietly, :==, :equal?, :!, :!=, :instance_eval, :instance_exec, :__send__, :__id__]

It has all other methods other than **wait_until_exists**. Am I missing something.

This is how the kitchen yam looks like:

```
---
driver:
  name: ec2
  security_group_ids: ["xyz"]
  region: xyz
  require_chef_omnibus: true
  subnet_id: xyz
  instance_type: abc
  associate_public_ip: true
  interface: dns
  tags : { created_by : "test_kitchen" }
  aws_ssh_key_id: "xxx" 
  retryable_tries: 120

provisioner:
  name: chef_solo

platforms:
  - name: centos-6
    driver:
      image_id: "yyy"
      root_device_type: "zzz"
      transport:
        ssh_key: ~/xyz
        username: "ec2-user"

```
