### ISSUE TITLE
README wrong for image_id and image_search?

### ISSUE THREAD

**Issue by kierandoonan** [test-kitchen/kitchen-ec2#236]
Currently the README has the following structure for `image_id` and `image_search`:

```
platforms:
  - name: centos-7
    image_id: ami-96a818fe

platforms:
  - name: ubuntu-14.04
    image_search:
      owner-id: "099720109477"
      name: ubuntu/images/*/ubuntu-*-14.04*
```

When I try this, it only uses the name to search (`image_id` and `image_search` are ignored). 

The `.kitchen.yml` documentation has slightly different format that seems to work (https://docs.chef.io/config_yml_kitchen.html)

```
platforms:
  - name: centos-7
    driver:
      image_id: ami-96a818fe

platforms:
  - name: ubuntu-14.04
    driver:
      image_search:
        owner-id: "099720109477"
        name: ubuntu/images/*/ubuntu-*-14.04*
```
