### ISSUE TITLE
kitchen converge skips past chef-client install without error on server 2008 r2

### ISSUE THREAD

**Issue by rayj-pgi** [test-kitchen/kitchen-ec2#241]
hey team,

 I'm running into an issue where kitchen fails to install the chef-client on server 2008 r2 in ec2. The kitchen run doesn't produce an error until when it fails starting `chef-client.bat`. After waiting for the `downloading` step I can see that it moves past the `installing` step too quickly to have been successful, but there is no error at that point.

``` shell
-----> Starting Kitchen (v1.6.0)
-----> Creating <default-windows-2008r2sp1>...

       Instance <i-xxxxxx0> requested.
       Polling AWS for existence, attempt 0...
       Attempting to tag the instance, 0 retries
       EC2 instance <i-xxxxxx0> created.
       Waited 0/1600s for instance <i-7ab388a0> to become ready.
       ...
       EC2 instance <i-xxxxxx0> ready.
       [WinRM] Established

           Directory: C:\chef\ohai\hints

       Mode                LastWriteTime     Length Name
       ----                -------------     ------ ----
       -a---         3/26/2016  12:13 AM          0 ec2.json

       Finished creating <default-windows-2008r2sp1> (2m39.26s).
-----> Converging <default-windows-2008r2sp1>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus ()

       Downloading package from https://opscode-omnibus-packages.s3.amazonaws.com/windows/2012r2/i386/chef-client-12.8.1-1-x86.msi

       Download complete.

       Successfully verified C:\Users\ADMINI~1\AppData\Local\Temp\chef-.msi

       Installing Chef Omnibus package C:\Users\ADMINI~1\AppData\Local\Temp\chef-.msi

       Transferring files to <default-windows-2008r2sp1>
$$$$$$ &amp; : The term 'C:\opscode\chef\bin\chef-client.bat' is not recognized as the
$$$$$$ name of a cmdlet, function, script file, or operable program. Check the
$$$$$$ spelling of the name, or if a path was included, verify that the path is
$$$$$$ correct and try again.
$$$$$$ At line:4 char:3
$$$$$$ + &amp; $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config
$$$$$$ $env:T ...
$$$$$$ +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : ObjectNotFound: (C:\opscode\chef\bin\chef-client
$$$$$$    .bat:String) [], CommandNotFoundException
$$$$$$     + FullyQualifiedErrorId : CommandNotFoundException
```

This same `.kitchen.yml` works with a server 2012 R2 instance.

.kitchen.yml

``` yaml

---
driver:
  name: ec2
  aws_ssh_key_id: XXXXXXXXX
  security_group_ids: ["sg-xxxxxxxx"]
  region: us-west-2
  instance_type: c4.large
  iam_profile_name: XXXXXX-ServerProfile-1LDLIF9XXXXX
  subnet_id: subnet-xxxxxxx
  retryable_tries: 200
  retryable_sleep: 8
  user_data: |
    <powershell>
    @'
    Start-Transcript -Path "C:\\Program Files\\Amazon\\Ec2ConfigService\\Logs\\user-data-bootstrap.log"

    Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force

    cmd.exe /c winrm quickconfig -q
    cmd.exe /c winrm quickconfig '-transport:http'
    cmd.exe /c winrm set "winrm/config" '@{MaxTimeoutms="1800000"}'
    cmd.exe /c winrm set "winrm/config/winrs" '@{MaxMemoryPerShellMB="1024"}'
    cmd.exe /c winrm set "winrm/config/service" '@{AllowUnencrypted="true"}'
    cmd.exe /c winrm set "winrm/config/client" '@{AllowUnencrypted="true"}'
    cmd.exe /c winrm set "winrm/config/service/auth" '@{Basic="true"}'
    cmd.exe /c winrm set "winrm/config/client/auth" '@{Basic="true"}'
    cmd.exe /c winrm set "winrm/config/service/auth" '@{CredSSP="true"}'
    cmd.exe /c winrm set "winrm/config/listener?Address=*+Transport=HTTP" '@{Port="5985"}'
    cmd.exe /c netsh advfirewall firewall set rule group="remote administration" new enable=yes
    cmd.exe /c netsh firewall add portopening TCP 5985 "Port 5985"
    cmd.exe /c sc config winrm start= auto

    Stop-Transcript
    '@ | Powershell.exe -NoProfile -
    </powershell>


provisioner:
  name: chef_zero

platforms:
  - name: windows-2008r2sp1
    transport:
      ssh_key: ~/keys/XXXXXXX.pem
      username: Administrator

suites:
  - name: default
    run_list:
      - recipe[kitchen-ec2-temp::default]
    attributes:
```

If I install the chef-client manually in `user_data` I can get server 2008 R2 to work.

``` powershell
$url = "https://opscode-omnibus-packages.s3.amazonaws.com/windows/2012r2/i386/chef-client-12.8.1-1-x86.msi"
$output = "c:\\chef\\tmp\\chef-client-12.8.1-1-x86.msi"

Invoke-WebRequest -Uri $url -OutFile $output
Start-Process -file c:\\chef\\tmp\\chef-client-12.8.1-1-x86.msi -arg /qn -passthru | wait-process
```
