### ISSUE TITLE
Cannot get kitchen.yaml to recognize image_id

### ISSUE THREAD

**Issue by karnold** [test-kitchen/kitchen-ec2#244]
The following is the only configuration I have gotten to even run so far, however it does not recognize the image_id in my configuration and just pulls a generic ubuntu image instead:

```

---
driver:
  name: ec2
  aws_ssh_key_id: sfmoma_s3
  transport.ssh_key: ~/.ssh/sfmoma-aws.pem
  region: us-west-2
  availability_zone: a
  require_chef_omnibus: true

transport:
    ssh_key: ~/.ssh/sfmoma-aws.pem

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    image_id: ami-4ad3242a
    transport.username: ubuntu

suites:
  - name: bamboo-testing-instance
    run_list:
      - recipe[storyscreens::django-app]
    attributes:
```

In issue https://github.com/test-kitchen/kitchen-ec2/issues/236 it presents the following configuration: 

```
platforms:
  - name: centos-7
    driver:
      image_id: ami-96a818fe
```

which i try updating the name and image_id value but that fails with the following error:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [undefined method `username' for nil:NilClass]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [undefined method `username' for nil:NilClass]
D      ---Nested Exception---
D      Class: NoMethodError
D      Message: undefined method `username' for nil:NilClass
D      ------Backtrace-------
D      /Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:288:in `update_username'
D      /Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:156:in `create'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:449:in `public_send'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:449:in `block in perform_action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:513:in `call'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:478:in `block in action'
D      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:477:in `action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:449:in `perform_action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:359:in `create_action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:348:in `block in transition_to'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:347:in `each'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:347:in `transition_to'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:160:in `verify'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:189:in `block in test'
D      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:185:in `test'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/command.rb:176:in `public_send'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
```

I am at a loss on this one.  Thanks in advance

**Comment by cheeseplus** [comment]
So the fix mentioned for the first issue is a doc fix that we totally need to get merged - as for the second issue I'm going to guess it's related to https://github.com/test-kitchen/kitchen-ec2/issues/225

/cc @jkeiser (as he probably knows more on this one)

**Comment by karnold** [comment]
Not sure if this is helpful in diagnosing the problem.  but for shits and giggles I took out the username property all together and used the following config:

```
---
driver:
  name: ec2
  aws_ssh_key_id: sfmoma_s3
  transport.ssh_key: ~/.ssh/sfmoma-aws.pem
  region: us-west-2
  availability_zone: a
  require_chef_omnibus: true


transport:
    ssh_key: ~/.ssh/sfmoma-aws.pem

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
        image_id: ami-4ad3242a

suites:
  - name: bamboo-testing-instance
    run_list:
      - recipe[storyscreens::django-app]
    attributes:

```

And it still threw the "Message: Failed to complete #create action: [undefined method `username' for nil:NilClass]" exception

**Comment by cheeseplus** [comment]
Going to try to repro this one if @jkeiser doesn't beat me to it but the only thing jumping out at me right now is the usage of OSX system ruby and the fact it's 2.0.0. We don't test 2.0.0 in tk-core (or most places anymore) because of big issues with that release (on top of the sad state of nearly every distro/OS version of Ruby).

Could be a red herring but that is the only thing that strikes me as off at a glance.

**Comment by karnold** [comment]
Im playing around in the config to see if I can find any clues.  here is some more debug info:

NOTE: added driver.username:
config:
```
---
driver:
  name: ec2
  aws_ssh_key_id: sfmoma_s3
  transport.ssh_key: ~/.ssh/sfmoma-aws.
  username: ubuntu
  region: us-west-2
  availability_zone: a
  require_chef_omnibus: true
  image_id: ami-4ad3242a
```

error:
```
/Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:91:in `validation_error': ERROR: The driver[Kitchen::Driver::Ec2] config key `username` has been removed, please use `transport.username` (RuntimeError)
```

output of config in "/Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:289:in `update_username'"

```
{
   :name=>"ec2", 
   :aws_ssh_key_id=>"sfmoma_s3", 
   :"transport.ssh_key"=>"~/.ssh/sfmoma-aws.pem", 
   :"transport.username"=>"ubuntu", 
    :region=>"us-west-2", 
    :availability_zone=>"a", 
    :image_id=>"ami-4ad3242a", 
    :kitchen_root=>"/Users/karnold/Dropbox/src/SFMOMA-DevOps/chef-repo/cookbooks/storyscreens", 
    :test_base_path=>"/Users/karnold/Dropbox/src/SFMOMA-DevOps/chef-repo/cookbooks/storyscreens/test/integration", 
    :log_level=>:debug, 
    :shared_credentials_profile=>nil, 
    :instance_type=>#<Proc:0x007fdf2285b430@/Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:52>, 
    :ebs_optimized=>false, 
    :security_group_ids=>nil, 
    :tags=>{"created-by"=>"test-kitchen"}, 
    :user_data=>#<Proc:0x007fdf2285b1b0@/Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:58>, 
    :private_ip_address=>nil, 
    :iam_profile_name=>nil, 
    :spot_price=>nil, 
    :block_duration_minutes=>nil, 
    :retryable_tries=>60, 
    :retryable_sleep=>5, 
    :aws_access_key_id=>nil, 
    :aws_secret_access_key=>nil, 
    :aws_session_token=>nil, 
    :image_search=>nil, 
    :username=>nil, 
    :associate_public_ip=>nil, 
    :interface=>nil, 
    :http_proxy=>nil, 
    :retry_limit=>3
}
```


So for posterity I try the following config and end up right back at square one:

```
---
driver:
  name: ec2
  aws_ssh_key_id: sfmoma_s3
  transport.ssh_key: ~/.ssh/sfmoma-aws.pem
  transport.username: ubuntu
  region: us-west-2
  availability_zone: a
  require_chef_omnibus: true
  image_id: ami-4ad3242a
```

error:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [undefined method `username' for nil:NilClass]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [undefined method `username' for nil:NilClass]
D      ---Nested Exception---
D      Class: NoMethodError
D      Message: undefined method `username' for nil:NilClass
D      ------Backtrace-------
D      /Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:289:in `update_username'
D      /Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:156:in `create'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:449:in `public_send'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:449:in `block in perform_action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:513:in `call'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:478:in `block in action'
D      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:477:in `action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:449:in `perform_action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:359:in `create_action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:348:in `block in transition_to'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:347:in `each'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:347:in `transition_to'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:160:in `verify'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:189:in `block in test'
D      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/instance.rb:185:in `test'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/command.rb:176:in `public_send'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.7.1/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
```

output of config in "/Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:289:in `update_username'"
```
{
    :name=>"ec2", 
    :aws_ssh_key_id=>"sfmoma_s3", 
    :"transport.ssh_key"=>"~/.ssh/sfmoma-aws.pem", 
    :"transport.username"=>"ubuntu", 
    :region=>"us-west-2", 
    :availability_zone=>"a", 
    :image_id=>"ami-4ad3242a", 
    :kitchen_root=>"/Users/karnold/Dropbox/src/SFMOMA-DevOps/chef-repo/cookbooks/storyscreens", 
    :test_base_path=>"/Users/karnold/Dropbox/src/SFMOMA-DevOps/chef-repo/cookbooks/storyscreens/test/integration", 
    :log_level=>:debug, 
    :shared_credentials_profile=>nil, 
    :instance_type=>#<Proc:0x007fa58216b1e0@/Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:52>, 
    :ebs_optimized=>false, 
    :security_group_ids=>nil, 
    :tags=>{"created-by"=>"test-kitchen"}, 
    :user_data=>#<Proc:0x007fa58216b050@/Library/Ruby/Gems/2.0.0/gems/kitchen-ec2-1.0.0/lib/kitchen/driver/ec2.rb:58>, 
    :private_ip_address=>nil, 
    :iam_profile_name=>nil, 
    :spot_price=>nil, 
    :block_duration_minutes=>nil, 
    :retryable_tries=>60, 
    :retryable_sleep=>5, 
    :aws_access_key_id=>nil, 
    :aws_secret_access_key=>nil, 
    :aws_session_token=>nil, 
    :image_search=>nil, 
    :username=>nil, 
    :associate_public_ip=>nil, 
    :interface=>nil, 
    :http_proxy=>nil, 
    :retry_limit=>3
}
```

hopefully some of that info is useful

**Comment by karnold** [comment]
Finally made progress.  From what I have figured out this might just be an issue in documentation.  The following configuration finally worked for me

```
---
driver:
  name: ec2
  aws_ssh_key_id: sfmoma_s3
  region: us-west-2
  availability_zone: a
  require_chef_omnibus: true

transport:
    ssh_key: ~/.ssh/sfmoma-aws.pem

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    transport:
        username: ubuntu
    driver:
        image_id: ami-4ad3242a

suites:
  - name: default
    run_list:
      - recipe[storyscreens::django-app]
    attributes:
```

**Comment by cheeseplus** [comment]
Glad you got this resolved as I was having issues trying to repro locally. We've got a documentation pass coming up for all the kitchen things but I'll see if we can get this one fixed sooner rather than later.

**Comment by jkeiser** [comment]
@cheeseplus what's the documentation issue here? I'd like to reopen this if there is a genuine backcompat issue, even though I'm super glad @karnold is fixed.

**Comment by jkeiser** [comment]
I'mma reopen it just for the moment since I'm not sure whether to mark it Bug or Question; I'll re-close once we close the loop on this.

**Comment by BenLiyanage** [comment]
100% Agree that this is a documentation issue.  I have independently figured out that the following configuration works correctly:

```
transport:
  username: ec2-user

platforms:
  - name: whatever
    driver:
      image_id: ami-8fcee4e5
```

By correlation it also makes sense that this works from @karnold (also a little cleaner):

```
platforms:
  - name: ubuntu-14.04
    transport:
        username: ubuntu
    driver:
        image_id: ami-4ad3242a
```

If you want I can open up a PR to fix the Readme and we can discuss more specifically what the documentation *should* say.  I think it'd also be good to have an example yml that shows the full nested configuration, and where you can provide a default value (aka like I provided a default value at the transport layer with my first example).
