### ISSUE TITLE
upgrading to tk 1.7 breaks ec2 plugin

### ISSUE THREAD

**Issue by kzw** [test-kitchen/kitchen-ec2#246]
I am now getting 
```

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [parameter validator found 3 errors:
  - unexpected value at params[:block_device_mappings][0][:ebs_device_name]
  - unexpected value at params[:block_device_mappings][0][:ebs_volume_size]
  - unexpected value at params[:block_device_mappings][0][:ebs_delete_on_termination]]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

I was actually getting earlier 

```
>>>>>> Message: Failed to complete #create action: [undefined method `username' for nil:NilClass]

```
But I tried the same thing as issue #244 got rid of this `username` problem.

My original kitchen yml is 
```
driver:
  vm_hostname: 'test-kitchen-instance-99.pelotime.com'
  name: <%= ENV['KITCHEN_DRIVER'] || 'vagrant' %>
  image_id: <%= ENV['KITCHEN_AMI'] || 'ami-32d4fc58' %>
  shared_credentials_profile: kitchen-jenkins
  transport:
    ssh_key: ~/.ssh/id_rsa
  instance_type: <%= ENV['KITCHEN_INSTANCE_TYPE'] || 'm4.large' %>
  availability_zone: a
  associate_public_ip: true
  subnet_id: 'subnet-3cb18b17'
  box: peloton-ubuntu
  box_url: http://docker.pelotime.com/peloton-ubuntu.tgz
  security_group_ids:
  - sg-f664f190
  require_chef_omnibus: 12.5.1
  block_device_mappings:
   - ebs_device_name: /dev/sda1
     ebs_volume_size: 8
     ebs_delete_on_termination: true
platforms:
- name: 'ubuntu-12.04'
provisioner:
  client_rb:
    node_name: 'test-kitchen-instance-99.pelotime.com'
    environment: production
    file_atomic_update: false
  encrypted_data_bag_secret_key_path: <%= ENV['KITCHEN_DATA_BAG_SECRET_PATH'] || '~/.chef/encrypted_data_bag_secret' %>
  data_path: test/shared
  name: chef_zero
suites:
- name: global-check
  run_list:
  - recipe[global-check]
```
