### ISSUE TITLE
how do I do an image search for amazon linux?

### ISSUE THREAD

**Issue by grimm26** [test-kitchen/kitchen-ec2#254]
I assumed this would work in the platforms section, it does not.

```
  - name: amazon
    image_search:
      owner_id: 137112412989
      name: amazon/amzn-ami-hvm-*.x86_64-gp2
```

It keeps giving me ubuntu, which seems to be the default.
