### ISSUE TITLE
support vpc id?

### ISSUE THREAD

**Issue by moogoos** [test-kitchen/kitchen-ec2#256]
We have a default vpc that is setup for a different function than what I would want to use kitchen tests for. Is there a flag to specify vpc id in kitchen.yml. I've tried vpc: <vpc_id> and vpc_mode: true and I still get the default. 

There's also the issue if someone deleted their default they error out also. We should be able to specify a VPC specifically.

**Comment by iiro** [comment]
We never use default VPC's - we delete those from new accounts the first thing.

They way to configure which VPC to use is the subnet_id. This works. No need to define the VPC.

**Comment by DI-DaveGoodine** [comment]
@iiro When I try use subnet_id, I get an error on kitchen create:
```
[15:46:36 di_mongodb  (master)] $ kitchen create
-----> Starting Kitchen (v1.10.0)
-----> Creating <default-ubuntu-1404>...
       Detected platform: ubuntu version 14.04 on x86_64. Instance Type: m3.medium. Default username: ubuntu (default).
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [The parameter groupName cannot be used with the parameter subnet] on default-ubuntu-1404
>>>>>> ----------------------
```

Here is my .kitchen.yml:
```
---
driver:
  name: ec2
  security_group_ids: ["sg-03af1366,sg-cfcf8faa"]
  subnet_id: subnet-61dd7404
  region: us-west-1
  availability_zone: c
  require_chef_omnibus: true
  instance_type: m3.medium
  interface: dns

transport:
  ssh_key: ~/.ssh/cm-key-ubuntu-aws-openstack.pem

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-5c120b19

suites:
  - name: default
    run_list:
      - recipe[di_mongodb::default]
    attributes:
```
