### ISSUE TITLE
`kitchen login` fails if ssh_key is a relative path.

### ISSUE THREAD

**Issue by markbate** [test-kitchen/kitchen-ec2#26]
I'm not entirely sure where this bubbles up from (might be a test-kitchen issue), but kitchen login doesn't seem to like relative paths for ssh keys.

Full path:

``` yaml
- name: ec2-ubuntu-12.04
  driver_name: ec2
  driver_plugin: ec2
  driver_config:
    image_id: ami-ad3660c4 # 64-bit instance-store backed
    username: ubuntu
    ssh_key: ~/Users/markbate/.ec2/test-kitchen.pem
```

The following should work fine:

``` yaml
kitchen converge default-ec2-ubuntu-1204
kitchen login default-ec2-ubuntu-1204
```

If you set it a relative path:

``` yaml
- name: ec2-ubuntu-12.04
  driver_name: ec2
  driver_plugin: ec2
  driver_config:
    image_id: ami-ad3660c4 # 64-bit instance-store backed
    username: ubuntu
    ssh_key: ~/.ec2/test-kitchen.pem
```

The following will converge, but not login.

```
kitchen converge default-ec2-ubuntu-1204
kitchen login default-ec2-ubuntu-1204
```

Error message is:

```
Warning: Identity file ~/.ec2/test-kitchen.pem not accessible: No such file or directory.
Permission denied (publickey).
```

Tests should also work fine, it's just the login that doesn't expand the path.
