### ISSUE TITLE
Kitchen client throws SSH auth error during instance creation - can ssh into the target manually

### ISSUE THREAD

**Issue by davidcpell** [test-kitchen/kitchen-ec2#261]
I'm using Kitchen on an Amazon EC2 workstation to generate other EC2 instances for testing Chef code. The problem I'm having is that Kitchen seems unable to connect to the created instances over SSH despite the fact that when I kill the `kitchen create` process I can manually SSH into the instance that Kitchen created but couldn't then log into.  

When I run `kitchen create default-amazon-linux -l debug` this is the error I'm seeing during the SSH stage:

```
D      [SSH] opening connection to ec2-user@ec2-52-41-249-5.us-west-2.compute.amazonaws.com<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :user=>"ec2-user"}>
D      [SSH] connection failed (#<Net::SSH::AuthenticationFailed: Authentication failed for user ec2-user@ec2-52-41-249-5.us-west-2.compute.amazonaws.com>)
       Waiting for SSH service on ec2-52-41-249-5.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
```

But if I copy and paste that host information into my terminal after stopping the `create` process I am able to login:

```
[ec2-user@ip-172-31-29-125 kitchen-workshop]$ ssh -i ~/.ssh/ec2-user ec2-user@ec2-52-41-249-5.us-west-2.compute.amazonaws.com
Last login: Thu Jun 30 14:22:35 2016 from ip-172-31-29-125.us-west-2.compute.internal

       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-ami/2016.03-release-notes/
1 package(s) needed for security, out of 3 available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-172-31-31-221 ~]$
```

I've double- and triple- and quadruple-checked my `.kitchen.yml` config but can't see anything wrong, so I was wondering if someone here might be able to help or if there's something else going on in `kitchen-ec2` itself that might not be working correctly (note: I've used `kitchen-ec2` successfully with my OSX localhost as the workstation...now I'm using an EC2 instance as the workstation for the first time). 

Here is my config:

```
---
driver:
  name: ec2
  region: us-west-2
  aws_ssh_key_id: ec2-user
  transport.ssh_key: /home/ec2-user/.ssh/ec2-user
  security_group_ids: [ "sg-2044d546" ] 
  subnet_id: subnet-af8866d8
  tags:
    Name: kitchen-workshop-target
    Owner: david.pell

provisioner:
  name: chef_solo

platforms:
  - name: amazon-linux
    driver:
      image_id: ami-f303fb93
    transport:
      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[git]
    attributes:
```

I've ensured that the target instances are in the same subnet as my workstation and have attached a security group that has Inbound rules that list the public and private IP addresses of my workstation. I can tell from the EC2 console that the subnet and security group are being assigned correctly, and obviously the security group works because I can manually SSH from the workstation into the target. So with all that being the case...I'm really stumped here!! Any ideas??
