### ISSUE TITLE
Might be leaving orphaned EBS volumes

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/kitchen-ec2#30]
I ended up with 51 unattached volumes after a day of testing.

**Comment by akuzminsky** [comment]
The bug still exists 
```
$ chef gem list | grep -e ec2 -e kitchen
...
kitchen-ec2 (3.2.0)
...
test-kitchen (2.3.3)
```
```
---
driver:
  name: ec2
  iam_profile_name: kitchen-test
```
After `kitchen test` the volume didn't get destroyed.

<img width="1552" alt="Screenshot 2020-04-25 22 57 22" src="https://user-images.githubusercontent.com/1763754/80299299-308a8180-8748-11ea-8ab8-25cf7b241fa0.png">
