### ISSUE TITLE
Pulling password for default administrator user on windows fails

### ISSUE THREAD

**Issue by scotthain** [test-kitchen/kitchen-ec2#312]
```
  - name: windows-2012r2
    driver:
      image_id: ami-09f47d69
      aws_ssh_key_id: <key-name>
    transport:
      name: winrm
      ssh_key: <key-location>
```

^ this should automatically grab the Administrator password that is randomly generated but we run into an issue. See: https://gist.github.com/scotthain/ae88f9aad205a51814fb81a24e5dd3b5

The specific error output is:
```
       Waited 70/300s for instance <i-048c29af82e75aee0> to become ready.
       Waited 0/300s for instance <i-048c29af82e75aee0> to fetch windows admin password.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [padding check failed] on slave-windows-2012r2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

One way to work around this is to specify transport username and password. (This creates a new user with a known password and thus never hits the code path that fails). Example:

```
  - name: windows-2012r2
    driver:
      image_id: ami-09f47d69
      aws_ssh_key_id: <key name>
    transport:
      name: winrm
      ssh_key: <key loc>
      username: build
      password: 'hooray'
```
