### ISSUE TITLE
Kitchen failure when adding spot_price

### ISSUE THREAD

**Issue by Evesy** [test-kitchen/kitchen-ec2#328]
Hi,

When trying to specify a spot price in my .kitchen.yml I receive the below error upon running any kitchen converge/test/verify commands:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [unexpected value at params[:launch_specification][:placement][:tenancy]]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Some environment info:

```
Test Kitchen version 1.4.2
kitchen-cloudstack (0.22.0)
kitchen-ec2 (1.3.2)
```

My .kitchen.yml is as below -- If I comment out the `spot_price` parameter kitchen runs successfully.

```
---
driver:
  name: ec2
  aws_ssh_key_id: kitchen
  subnet_filter:
    tag: 'Name'
    value: 'subnet-private-b'
  security_group_ids: ["<sg-id>", "<sg-id>"]
  region: eu-west-1
  instance_type: t2.micro
  spot_price: 0.010

transport:
  ssh_key: ~/.ssh/kitchen

platforms:
  - name: centos-7
    driver:
      image_id: "<ami-id>"

suites:
  - name: default
    provisioner:
      name: chef_solo
      require_chef_omnibus: <%= ENV['REQUIRE_CHEF_OMNIBUS'] %>
      data_bags_path: <%= ENV['DATA_BAGS_PATH'] %>
      data_path: test/shared
    run_list:
      - recipe[filebeat::default]
    attributes: {}

```

Any help would be appreciated

Cheers!

**Comment by Evesy** [comment]
I have also tried with an m3.medium instance as I don't actually think t2.micro's are available as spot instances, however the results are the same.

**Comment by Evesy** [comment]
This occurs when setting default & dedicated as tenancy type.

When setting 'host' as the tenancy type (Which is unsupported as per http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Types/SpotPlacement.html), Kitchen successfully launches a spot instance with default tenancy type.

**Comment by irvingpop** [comment]
this appears to have been fixed along the way and seems to work quite nicely ( tested on ChefDK 2.5.3):

```
---
driver:
  name: ec2
  region: <%= ENV['AWS_REGION'] || 'us-east-1' %>
  instance_type: m5.large
  spot_price: 0.0960
  associate_public_ip: true
  interface: public
  ebs_optimized: true
  block_device_mappings:
  - device_name: /dev/sda1
    ebs:
      volume_type: gp2
      volume_size: 50
      delete_on_termination: true
```
