### ISSUE TITLE
kitchen converge fails on AWS ec2 windows instances

### ISSUE THREAD

**Issue by ksandrmatveyev** [test-kitchen/kitchen-ec2#332]
Hi everyone,
When I want to test my cookbooks on ec2 windows (kitchen converge), I get failure:

```
       System Info:
       ------------
       chef_version=13.2.20
       platform=windows
       platform_version=6.3.9600
       ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
       program_name=C:/opscode/chef/bin/chef-client
       executable=C:/opscode/chef/bin/chef-client


       Running handlers:
       [2017-07-27T07:57:37+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-07-27T07:57:37+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 04 seconds
       [2017-07-27T07:57:37+00:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-07-27T07:57:37+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-07-27T07:57:37+00:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-windows-2012r2>.  Please see .kitchen/logs/default-windows-2012r2.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Log:
```
[2017-07-26T20:57:27.155512 #6785] ERROR -- default-windows-2012r2: Converge failed on instance <default-windows-2012r2>.
E, [2017-07-26T20:57:27.155761 #6785] ERROR -- default-windows-2012r2: ------Exception-------
E, [2017-07-26T20:57:27.155970 #6785] ERROR -- default-windows-2012r2: Class: Kitchen::ActionFailed
E, [2017-07-26T20:57:27.156177 #6785] ERROR -- default-windows-2012r2: Message: WinRM exited (1) for command: [$env:TEST_KITCHEN = "1"
$env:PATH = try {
[System.Environment]::GetEnvironmentVariable('PATH','Machine')
} catch { $env:PATH }
& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889 ; exit $LastExitCode]
```

when run kitchen converge on Linux instances are everything OK.  And if I use knife for ec2 windows nodes, everything is good, too

My .kitchen.yaml:
```
---
driver:
  name: ec2
  aws_ssh_key_id: key
  region: us-east-1
  availability_zone: a
  subnet_id: subnet-d1sdd799
  instance_type: t2.micro
  image_id: ami-d79d92c1
  security_group_ids: sg-c8das5b9
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /path/to/key.pem

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
```
