### ISSUE TITLE
Please login as the user "ubuntu" rather than the user "root".

### ISSUE THREAD

**Issue by IamGabrielWu** [test-kitchen/kitchen-ec2#354]
I did specify user as ubuntu in my kitchen.yml. why it still says login as ubuntu. 

```yaml
---
driver:
  name: ec2
  aws_ssh_key_id: gabrieltest
  instance_type: t2.micro
  security_group_ids: ["xxx"]
  region: us-east-1

provisioner:
  name: chef_zero
  require_chef_omnibus: "12.18.31"
  roles_path: ../../roles
  environments_path: ../../environments
  cookbook_path: ../../cookbooks
  data_bags_path: ../../data_bags
  solo_rb:
    environment: development

transport:
  ssh_key: /Users/gwu/awskeys/gabrieltest.pem
  username: ubuntu

platforms:
  - name: aws-ubuntu-16.04
    driver:
      image_id: ami-da05a4a0
    transport:
      username: ubuntu
```
