### ISSUE TITLE
kitchen verify needs ssh_key, kitchen converge works without it

### ISSUE THREAD

**Issue by runningman84** [test-kitchen/kitchen-ec2#355]
It looks like kitchen verify does not work without a ssh_key in the transport settings. Funny enough it works just fine for the login command:

```
➜  asy-base git:(master) ✗ kitchen login 16
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1038-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

24 packages can be updated.
11 updates are security updates.


Last login: Thu Nov 23 15:43:27 2017 from 145.228.183.127
ubuntu@ip-172-31-29-91:~$ logout
Connection to ec2-52-57-193-97.eu-central-1.compute.amazonaws.com closed.
➜  asy-base git:(master) ✗ kitchen verify 16
-----> Starting Kitchen (v1.17.0)
-----> Verifying <default-ubuntu-1604>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Transport error, can't connect to 'ssh' backend: SSH session could not be established] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

This is a pitty becase our jenkins slaves might not have a physical ssh private key in the filesystem because they rely on an external ssh-agent.

**Comment by cheeseplus** [comment]
We'd need your sanitized `.kitchen.yml` before being able to validate what you're seeing.

**Comment by runningman84** [comment]
Ok here you go:

```
#.kitchen.yml
---
driver:
  name: vagrant
  provision: true

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  client_rb:
    lockfile: "#{File.join(Dir.tmpdir, 'chef-client-running.pid')}"
  solo_rb:
    lockfile: "#{File.join(Dir.tmpdir, 'chef-client-running.pid')}"
  require_chef_omnibus: 12

verifier:
  name: inspec
  <% if ENV['CI'] == "jenkins" %>
  format: junit
  output: "kitchen-reports/kitchen_report_%{suite}_%{platform}_inspec.xml"
  <% else %>
  format: cli
  <% end %>

transport:
  name: speedy_ssh # default transport produces the same error

platforms:
  - name: ubuntu-16.04
    driver:
      box: asy/xenial64-lxc
      provider: lxc
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[sudo::default]
    attributes:
      authorization:
        sudo:
          users: ["vagrant", "kitchen"]
          passwordless: true
          include_sudoers_d: true


```


```
#.kitchen.local.yml
---
driver:
  name: ec2
  security_group_ids: ["<%= ENV.fetch('KITCHEN_EC2_SECURITY_GROUP', 'sg-aaaaaaaa') %>"]
  region: <%= ENV.fetch('KITCHEN_EC2_REGION', 'eu-central-1') %>
  availability_zone: <%= ENV.fetch('KITCHEN_EC2_AZ', 'a') %>
  require_chef_omnibus: true
  subnet_id: <%= ENV.fetch('KITCHEN_EC2_SUBNET', 'subnet-bbbbbbbbb') %>
  iam_profile_name: <%= ENV.fetch('KITCHEN_EC2_IAM_PROFILE', 'TestKitchenRole') %>
  instance_type: <%= ENV.fetch('KITCHEN_EC2_INSTANCE_TYPE', 't2.micro') %>
  aws_ssh_key_id: <%= ENV.fetch('KITCHEN_EC2_SSH_KEY_ID', "#{ENV.fetch('USER', '')}aws") %>
#  price: 0.6
  associate_public_ip: true
  interface: dns
  tags:
    Name: <%= "kitchen_test_#{File.basename(Dir.getwd)}" %>
    Cookbook: <%= File.basename(Dir.getwd) %>
    User: <%= ENV.fetch('USER', 'unknown') %>
    Timelimit: "<%= ENV.fetch('KITCHEN_EC2_TIMELIMIT', 20*60) %>" # 20 minute max runtime
  root_device_size: 10
  block_device_mappings:
  - device_name: /dev/sdf
    ebs:
      volume_type: gp2
      volume_size: 10
      delete_on_termination: true

transport:
  ssh_key: <%= "#{ENV['HOME']}/.ssh/#{ENV.fetch('KITCHEN_EC2_SSH_KEY_ID', "#{ENV.fetch('USER', '')}aws")}" %>
  connection_timeout: 10
  connection_retries: 5

platforms:
  - name: ubuntu-16.04
    driver:
      image_search:
        owner-id: "1234567890"
        name: "myimage*"
```
