### ISSUE TITLE
user_data does not seem to work in Test Kitchen

### ISSUE THREAD

**Issue by mlcooper** [test-kitchen/kitchen-ec2#369]
If I include a `user_data` script while using the aws cli, the user_data script runs as expected and produces the expect results in the instance that is stood up.  However, when the same `user_data` script is included in the test kitchen config, it does not take effect.

This works successfully:
```
aws ec2 run-instances --image-id ami-xxxxxx --count 1 --instance-type t2.micro --key-name <redacted> --subnet-id subnet-xxxxxxx --security-group-ids sg-xxxxx sg-xxxxxx --user-data file://cloud-init-script.sh
```
If I do `-l debug` in test kitchen, I can see that `user_data` is getting passed in, but in the resulting instance, the settings that should be there are not.
```
Creating EC2 instance in region us-west-2 with properties:
D      - instance_type = "t2.micro"
D      - ebs_optimized = false
D      - image_id = "ami-xxxxxx"
D      - key_name = "<redacted>"
D      - private_ip_address = nil
D      - placement = {:availability_zone=>"us-west-2c", :tenancy=>"default"}
D      - user_data = "ZmlsZTovL2Nsb3VkLWluaXQtc2NyaXB0LnNo\n"
D      - network_interfaces = [{:device_index=>0, :associate_public_ip_address=>false, :delete_on_termination=>true, :subnet_id=>"subnet-xxxxxxx", :groups=>["sg-xxxxxxx", "sg-xxxxxxxx"]}]
````
The `user_data` removes the expiration of a password for the user that test kitchen uses to login and also removes it's password.  But when TK spins up the instance, we still get the error that the users password has expired and must be reset.

My `.kitchen.yml` config:
```
platforms:
  - name: rhel7
    driver:
      image_id: ami-xxxxxx
      user_data: file://cloud-init-script.sh
```
The `cloud-init-script.sh` is in the same directory as the `.kitchen.yml` file.

**Comment by cheeseplus** [comment]
I don't believe `file://` is expected or handled, we know `user_data` works in some respect as this is how all Windows instances are spun up.

**Comment by mlcooper** [comment]
I went ahead and tried
```
platforms:
  - name: rhel7
    driver:
      image_id: ami-xxxxxx
      user_data: ./cloud-init-script.sh
```
And I also tried
```
platforms:
  - name: rhel7
    driver:
      image_id: ami-xxxxxx
      user_data: cloud-init-script.sh
```
But both result in the instance telling us the password has expired and must be changed (the user_data script is supposed to take care of that).

The `cloud-init-script.sh` lives in the same directory as the `.kitchen.yml` file.

**Comment by cheeseplus** [comment]
I have constructed a simple test:

test script is `user_data_script.sh`
```
#! /bin/bash
echo "user data srcript ran" >> /root/user_data_script.log
```

.kitchen.yml
```
---
driver:
  name: ec2
  region: us-west-1
  user_data: user_data_script.sh

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[kitchen_ec2]
```

After a kitchen converge (the cookbook doesn't do anything)
```
# cat /root/user_data_script.log
user data srcript ran
```

This seems to indicate the functionality is working as designed but without the contents of the script it's hard to say if something else is happening that would cause the script to be failing. Perhaps you could provide more detail about what is in the script or how exactly you're validating that nothing is being run on the remote system by `user_data`.

**Comment by mlcooper** [comment]
Our standard RHEL images come with a user called `cloud`.  The first time you ssh into an instance with this image, you are forced to change the password for `cloud`.  So for Test Kitchen purposes, we're trying to pass in a `user_data` script that blows away the password to `cloud` and changes its expiration time so that TK can continue on with the chef run.  At the AWS CLI it works, but in TK it hangs here indefinitely:
```
       EC2 instance <i-0axxxxxxxxxxxxx> ready (hostname: 10.x.x.x).
       Waiting for SSH service on 10.x.x.x:22, retrying in 3 seconds
       WARNING: Your password has expired.
       You must change your password now and login again!
       Changing password for user cloud.
```
The contents of our user_data script is
```
#!/bin/sh
chage -d $(date +%Y-%m-%d) cloud 
passwd --delete cloud
```

**Comment by cheeseplus** [comment]
How are you telling kitchen what user to use? I don't see any transport settings in any of the snippets provided.

**Comment by mlcooper** [comment]
Sorry I omitted the `transport` settings we have in place:
```
platforms:
  - name: rhel7
    driver:
      image_id: ami-xxxx
      user_data: cloud-init-script.sh
    transport:
      username: cloud
      # your private key for your AWS Key Pair (Network & Security --> Key Pairs)
      ssh_key: <%= ENV['AWS_KEYFILE'] %>
      name: rsync
      connection_timeout: 10
      connection_retries: 5
```
New debug output from today:
```
D      Creating EC2 instance in region us-west-2 with properties:
D      - instance_type = "t2.micro"
D      - ebs_optimized = false
D      - image_id = "ami-xxxxxxxxx"
D      - key_name = "<redacted>"
D      - private_ip_address = nil
D      - placement = {:availability_zone=>"us-west-2c", :tenancy=>"default"}
D      - user_data = "Li9jbG91ZC1pbml0LXNjcmlwdC5zaA==\n"
D      - network_interfaces = [{:device_index=>0, :associate_public_ip_address=>false, :delete_on_termination=>true, :subnet_id=>"subnet-xxxxxxx", :groups=>["sg-xxxxxxx", "sg-xxxxxxxx"]}]
```

**Comment by cheeseplus** [comment]
The base64 decodes to `./cloud-init-script.sh	` which means it's not recognizing that as a file, instead literally taking it as the string. Try `cloud-init-script.sh` and provide the user_data debug (or decode yourself https://www.base64decode.org/).

The other thing that stands out is the transport being used is `rsync` which is something we don't actively support.

**Comment by mlcooper** [comment]
In the debug output are you expecting to see the _contents_ of the file, or just `cloud-init-script.sh`?
I changed the settings to:
```
 - name: rhel7
    driver:
      image_id: ami-xxxxxx
      user_data: cloud-init-script.sh
    transport:
      username: cloud
      # your private key for your AWS Key Pair (Network & Security --> Key Pairs)
      ssh_key: <%= ENV['AWS_KEYFILE'] %>
      name: sftp
      connection_timeout: 10
      connection_retries: 5
```
And I decoded the `user_data` and it appears to have an extra character `'` in what got decoded.
```
D      Creating EC2 instance in region us-west-2 with properties:
D      - instance_type = "t2.micro"
D      - ebs_optimized = false
D      - image_id = "ami-xxxxx"
D      - key_name = "<redacted>"
D      - private_ip_address = nil
D      - placement = {:availability_zone=>"us-west-2c", :tenancy=>"default"}
D      - user_data = "Y2xvdWQtaW5pdC1zY3JpcHQuc2g=\n"
D      - network_interfaces = [{:device_index=>0, :associate_public_ip_address=>false, :delete_on_termination=>true, :subnet_id=>"subnet-xxxx", :groups=>["sg-xxxx", "sg-xxxx"]}]
```
