### ISSUE TITLE
doesn't invoke test while using ec2 driver

### ISSUE THREAD

**Issue by JigarJoshi** [test-kitchen/kitchen-ec2#37]
This is my `.kitchen.yml` looks like, if I switch driver back to `vagrant` it is able to create virtual box instance and invoke the tests on it

```

---
driver:
name: ec2
aws_access_key_id: SOME_KEY
aws_secret_access_key: SOME_KEY
aws_ssh_key_id: id_rsa-aws
ssh_key: /path/to/jigaraws.pem
security_group_ids: ["SOME_GROUP"]
region: us-west-2
availability_zone: us-west-2c
require_chef_omnibus: true
subnet_id: SOME_SUBNET

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[ci-somerecipe::default]
    attributes:
```

but if I use `ec2` driver it just exists with exit code `0` in less than a second and with following output

```
-----> Starting Kitchen (v1.2.1)
-----> Cleaning up any prior instances of <default-centos-64>
-----> Destroying <default-centos-64>...
       [Dummy] Destroy on instance=#<Kitchen::Instance:0x000001018bf248> with state={}
       Finished destroying <default-centos-64> (0m0.00s).
-----> Testing <default-centos-64>
-----> Creating <default-centos-64>...
       [Dummy] Create on instance=#<Kitchen::Instance:0x000001018bf248> with state={:my_id=>"default-centos-64-1392858588"}
       Finished creating <default-centos-64> (0m0.00s).
-----> Converging <default-centos-64>...
       [Dummy] Converge on instance=#<Kitchen::Instance:0x000001018bf248> with state={:my_id=>"default-centos-64-1392858588", :last_action=>"create"}
       Finished converging <default-centos-64> (0m0.00s).
-----> Setting up <default-centos-64>...
       [Dummy] Setup on instance=#<Kitchen::Instance:0x000001018bf248> with state={:my_id=>"default-centos-64-1392858588", :last_action=>"converge"}
       Finished setting up <default-centos-64> (0m0.00s).
-----> Verifying <default-centos-64>...
       [Dummy] Verify on instance=#<Kitchen::Instance:0x000001018bf248> with state={:my_id=>"default-centos-64-1392858588", :last_action=>"setup"}
       Finished verifying <default-centos-64> (0m0.00s).
-----> Destroying <default-centos-64>...
       [Dummy] Destroy on instance=#<Kitchen::Instance:0x000001018bf248> with state={:my_id=>"default-centos-64-1392858588", :last_action=>"verify"}
       Finished destroying <default-centos-64> (0m0.00s).
       Finished testing <default-centos-64> (0m0.01s).
-----> Kitchen is finished. (0m0.80s)
```

Did I miss something in configuration ? I am expecting it to spin up an instance on ec2 and execute bats test against it
