### ISSUE TITLE
allow specifying ports for generated security group

### ISSUE THREAD

**Issue by atheiman** [test-kitchen/kitchen-ec2#384]
the 2.0 change of a generated security group with only ssh or winrm open is a nice idea.

I think an improvement on it would be to allow specifying open inbound and outbound ports in kitchen.yml. I would just keep it simple and allow the user to specify an array of hashes that can be sent to [`securitygroup.authorize_ingress`](https://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/SecurityGroup.html#authorize_ingress-instance_method) and [`securitygroup.authorize_egress`](https://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/SecurityGroup.html#authorize_egress-instance_method)

```yaml
driver:
  name: ec2
  security_group_rules:
    ingress:
      - ip_permissions:
        - from_port: 1234
          ip_protocol: tcp
          ip_ranges:
          - cidr_ip: 0.0.0.0/0
          to_port: 1234
      - ip_permissions:
        - from_port: 5678
          ip_protocol: tcp
          to_port: 5678
        source_security_group_name: some-security-group
        source_security_group_owner_id: '505050505'
```
