### ISSUE TITLE
Provisioning is performed immediately without waiting for the scripts to complete

### ISSUE THREAD

**Issue by salvax86** [test-kitchen/kitchen-ec2#389]
We run "kitchen converge" with the ec2 driver and ansible_push provisioning. To initialize the host for provisioning, we run a init script next to the cloud_init through user_data. 
Unfortunately, the provisioning does not wait for the user_data init to complete, resulting in an error. Is it possible to do something so that the provisioning step does not run into error?

.kitchen.yml
```
driver:
  name: ec2
  region: us-east-2
  associate_public_ip: true
  user_data: init.sh

platforms:
  - name: test-kitchen
    driver:
       image_id: ami-4f80b52a

transport:
  ssh_key: ./keys/ansible_kitchen.pem
  username: ubuntu
  connection_timeout: 10
  connection_retries: 5
  max_ssh_sessions: 6

provisioner:
  name: ansible_push
  ansible_config: ./test/ansible.cfg
  chef_bootstrap_url: nil
  idempotency_test: true
  diff: true

suites:
  - name: default
    provisioner:
      playbook: "./test/integration/default/default.yml"
    verifier:
      name: inspec
      patterns:
        - "./test/integration/default/rancher_spec.rb"
```

init.sh

```
#!/bin/bash

i="0"
while [ $i -lt 15 ]
do
if [ $(fuser /var/lib/dpkg/lock) ]; then
  i="0"
fi
sleep 1
i=$[$i+1]
done

sudo apt-get update;

sudo apt-get install curl python python-pip python-requests git libffi-dev libssl-dev -y;

pip install docker-py;
```
