### ISSUE TITLE
SSH access fails with ProxyJump

### ISSUE THREAD

**Issue by gui-don** [test-kitchen/kitchen-ec2#406]
Hello,

It seems kitchen does not support SSH _ProxyJump_ option, or that I’m doing something wrong on the kitchen side.

Here is part of my `.kitchen.yml`:

```yaml
driver:
  […]
  name: ec2
  aws_ssh_key_id: "<%= ENV['AWS_SSH_KEY_ID'] %>"

transport:
  ssh_key: <%= ENV['AWS_SSH_KEY'] %>
  username: myuser

[…]
```
And my failing `~/.ssh/config` file:
```
And my ~/.ssh/config:
  Host bastion
        User myuser
        Hostname 8.8.8.8 # my true IP
        IdentityFile ~/.ssh/id_myidfile

  Host  10.10.*.*
        User myuser
        ProxyJump bastion
        IdentityFile ~/.ssh/id_myotheridfile
```
Of course, this works well when doing the ssh command by hand (e.g. `ssh 10.10.100.100`). But kitchen keeps trying to connect without success.

However, if I change `ProxyJump bastion` with `ProxyCommand ssh bastion -W %h:%p`, kitchen works as expected (ssh connection is possible).

This leads me to the conclusion that kitchen does not handle _ProxyJump_ option correctly. I can tolerate the _ProxyCommand_, but it’s not as sexy as _ProxyJump_. And I like sexyness.

Thank you for your work!
