### ISSUE TITLE
Support Windows Server 1709 and Windows 1803

### ISSUE THREAD

**Issue by xtimon** [test-kitchen/kitchen-ec2#428]
My platforms configuration:
```
platforms:
  - name: windows-1709
    driver:
      image_search:
        owner-id: "801119661308"
        name: Windows_Server-1709-English-Core-ContainersLatest-*
  - name: windows-1803
    driver:
      image_search:
        owner-id: "801119661308"
        name: Windows_Server-1803-English-Core-ContainersLatest-*
```

kitchen create doesn't work because user_data script fails:

```
out-file : Could not find a part of the path 'C:\Program Files\Amazon\Ec2ConfigService\Logs\kitchen-ec2.log'.
At C:\Users\Administrator\user_data.ps1:21 char:1
+ & winrm.cmd set winrm/config '@{MaxTimeoutms="1800000"}' >> $logfile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

out-file : Could not find a part of the path 'C:\Program Files\Amazon\Ec2ConfigService\Logs\kitchen-ec2.log'.
At C:\Users\Administrator\user_data.ps1:22 char:1
+ & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

out-file : Could not find a part of the path 'C:\Program Files\Amazon\Ec2ConfigService\Logs\kitchen-ec2.log'.
At C:\Users\Administrator\user_data.ps1:23 char:1
+ & winrm.cmd set winrm/config/winrs '@{MaxShellsPerUser="50"}' >> $log ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

out-file : Could not find a part of the path 'C:\Program Files\Amazon\Ec2ConfigService\Logs\kitchen-ec2.log'.
At C:\Users\Administrator\user_data.ps1:24 char:1
+ & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

out-file : Could not find a part of the path 'C:\Program Files\Amazon\Ec2ConfigService\Logs\kitchen-ec2.log'.
At C:\Users\Administrator\user_data.ps1:26 char:1
+ & netsh advfirewall firewall set rule name="Windows Remote Management ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

This path is not available `C:\Program Files\Amazon\Ec2ConfigService\Logs`
It would be great to have such command in user_data file start:

```
New-Item -ItemType Directory -Force -Path 'C:\Program Files\Amazon\Ec2ConfigService\Logs'
```
