### ISSUE TITLE
Kitchen is using ARM architecture for Ubuntu by default

### ISSUE THREAD

**Issue by axl89** [test-kitchen/kitchen-ec2#431]
Since today, and without changes on my kitchen (`v1.19.2`) configuration file, kitchen spawned ARM machines and failed.

## Relevant section of the configuration file

```
---
driver:
  name: ec2
  region: eu-west-1
  instance_type: t2.medium
  associate_public_ip: true
  interface: dns
  aws_ssh_key_id: AWSIreland
  block_duration_minutes: 60
  block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        volume_size: 12
        delete_on_termination: true


transport:
  ssh_key: ~/.ssh/AWSIreland.pem
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

provisioner:
  name: chef_zero
  product_name: chef
  client_rb:
    environment: integration

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
```

## CI output

```
$ kitchen test ^hextron-13.* -d always
-----> Starting Kitchen (v1.19.2)
-----> Cleaning up any prior instances of <hextron-13-full-test-ubuntu-1604>
-----> Destroying <hextron-13-full-test-ubuntu-1604>...
       Finished destroying <hextron-13-full-test-ubuntu-1604> (0m0.00s).
-----> Testing <hextron-13-full-test-ubuntu-1604>
-----> Creating <hextron-13-full-test-ubuntu-1604>...
       Detected platform: ubuntu version 16.04 on arm64. Instance Type: t2.medium. Default username: ubuntu (default).
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

-----> Destroying <hextron-13-full-test-ubuntu-1604>...
       Finished destroying <hextron-13-full-test-ubuntu-1604> (0m0.00s).
-----> Cleaning up any prior instances of <hextron-13-full-test-ubuntu-1804>
-----> Destroying <hextron-13-full-test-ubuntu-1804>...
       Finished destroying <hextron-13-full-test-ubuntu-1804> (0m0.00s).
-----> Testing <hextron-13-full-test-ubuntu-1804>
-----> Creating <hextron-13-full-test-ubuntu-1804>...
       Detected platform: ubuntu version 18.04 on arm64. Instance Type: t2.medium. Default username: ubuntu (default).
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

-----> Destroying <hextron-13-full-test-ubuntu-1804>...
       Finished destroying <hextron-13-full-test-ubuntu-1804> (0m0.00s).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 2 actions failed.
>>>>>>     Failed to complete #create action: [The requested configuration is currently not supported. Please check the documentation for supported configurations.] on hextron-13-full-test-ubuntu-1604
>>>>>>     Failed to complete #create action: [The requested configuration is currently not supported. Please check the documentation for supported configurations.] on hextron-13-full-test-ubuntu-1804
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
ERROR: Job failed: exit status 1
```
