### ISSUE TITLE
[windows] creates the instance, gets the password and waits forever

### ISSUE THREAD

**Issue by lmayorga1980** [test-kitchen/kitchen-ec2#438]
Why does it wait that long to return to the console.

```       
Waited 290/600s for instance <i-009de37f8d6706c41> to become ready.
Waited 295/600s for instance <i-009de37f8d6706c41> to become ready.
Waited 0/600s for instance <i-009de37f8d6706c41> to fetch windows admin password.
Retrieved Windows password for instance <i-009de37f8d6706c41>.
EC2 instance <i-009de37f8d6706c41> ready (hostname: <SOME_PRIVATE_IP>).
```

**Comment by cheeseplus** [comment]
It would be helpful if you could provide an illustration or defining "wait that long" as it's not clear if "forever" is an exaggeration or it's actually hanging perpetually. Typically this falls under "Windows Instances are generally slower to boot" but you can also provide an example `kitchen.yml` to show what instances sizes and AMIs you are utilizing.

You can also kick up the logging with `-l debug` to see more information.

**Comment by lmayorga1980** [comment]
My mistake here...

I had the user data pointing to port `5986` while keeping the transport on port `5985`

Switch my `kitchen.yml` to use the right port and transport and back in business.

```yaml
---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEYNAME'] %>
  region: us-east-1
  availability_zone: b
  instance_type: t2.medium
  associate_public_ip: false
  interface: private
  subnet_id: <%= ENV['AWS_SUBNET_ID']  %>
  security_group_ids: [ <%= ENV['AWS_SG_ID'] %> ]
  retryable_tries: 120
  shared_credentials_profile: saml
  user_data: user_data_windows_2016.ps1

verifier:
  name: inspec

transport:
    name: winrm
    port: 5986
    winrm_transport: ssl
    ssl: true
    ssh_key: ~/.ssh/<%= ENV['AWS_SSH_KEYNAME'] %>.pem
    connect_timeout: 60
    connection_retries: 5
    username: Administrator

platforms:
  - name: windows-2016
    driver:
      image_id: <%= ENV['AWS_AMI_ID'] %>

suites:
  - name: base
    verifier:
      inspec_tests:
        - test/base_spec.rb

```
