### ISSUE TITLE
AMI search provides wrong AMI for amazon linux

### ISSUE THREAD

**Issue by voroniys** [test-kitchen/kitchen-ec2#445]
In my .kitchen.yml I have the following:
```
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-*
```
and I expect it will provide me the latest AMI for amazonlinux 2, which is at the moment of writting  `amzn2-ami-hvm-2.0.20190115-x86_64-gp2`
Nevertheless I constantly getting very outdated image `amzn2-ami-hvm-2017.12.0.20180509-x86_64-gp2`
Accordingly to the README file I have to have the most recent one. Something wrong with sorting?

**Comment by cheeseplus** [comment]
Could you provide the kitchen-ec2 version details? Typically you can just name the platform `amazon-2` and it will execute this search which is a bit different from yours https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/aws/standard_platform/amazon2.rb#L30 the actual sorting hasn't much changed and you can see the decisions it's filtering on fairly easily in https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/aws/standard_platform.rb

**Comment by voroniys** [comment]
My version is
kitchen-ec2 (2.4.0)
And I fully disagree with you that my query is not specific enough. You set the criteria:
- HVM images over paravirtual
- SSD support over magnetic drives
- 64-bit over 32-bit
- The most recently created image (to pick up patch releases)
Accordingly to this criteria I should never get `amzn2-ami-hvm-2017.12.0.20180509-x86_64-gp2`, just because `ami-hvm-2.0.20190115-x86_64-gp2` is much more recent while 3 first conditions are the same.
Just from experiment I conclude that the 4th criteria implemented based on image name, and not on creation date.
I took this conclusion based on the fact that with search criteria 
name: amzn2-ami-hvm-*-x86_64-gp2
I'm getting outdated AMI, while with
name: amzn2-ami-hvm-2.0.*-x86_64-gp2
I'm getting the right one.

**Comment by cheeseplus** [comment]
I'm unable to reproduce this with either configuration in the `us-east-1` region:

```
platforms:
  - name: amazon2
  - name: search_1
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-*
  - name: search_2
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-hvm-*-x86_64-gp2
```
All of the above iterations I get `amzn2-ami-hvm-2.0.20190115-x86_64-gp2 (ami-035be7bafff33b6b6)`

If you are able to reproduce this reliably then I suspect it might be region specific or there are other mitigating configuration factors. We would need a full `kitchen.yml`, the logs from the run, the region being used, and ideally output from `kitchen diagnose`. Provide those and we can investigate further. I'd also double check the version of `kitchen-ec2` as there were fixes for Amazon 2 that shipped in 2.4.0 which is what the above configuration was run against.

**Comment by voroniys** [comment]
I'm using eu-west-1 (Ireland) region.

**Comment by cheeseplus** [comment]
I'll try to replicate there, what I suspect is that how Amazon loaded/tagged/dated the images there is inherently bad and we're just passing along said "bad data". If that's the case then it's more an AWS problem than our sorting but I'll see if I can figure out why and if there is any mitigation w/o accounting for each region specifically (which would be a nightmare).

**Comment by cheeseplus** [comment]
Still unable to replicate with the following condfiguration

```
driver:
  name: ec2
  region: "eu-west-1"

provisioner:
  name: chef_zero

platforms:
  - name: amazon2
    # - name: amazon2-2019
  - name: search-1
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-*
  - name: search-2
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-hvm-*-x86_64-gp2
```
Test-kitchen gets the expected `amzn2-ami-hvm-2.0.20190218-x86_64-gp2 (ami-0838da7c1467f590c)` for all three permutations. At this point I feel like we should verify that you're actually using the version of kitchen-ec2 expected and also get the output of `kitchen diagnose`.

If using ChefDK:
`chef -v`
`chef gem list kitchen-ec2`

If using your own Ruby/Bundler:
`which kitchen`
`kitchen --version`
`gem list kitchen-ec2`
