### ISSUE TITLE
centos search filters allow undesirable images through

### ISSUE THREAD

**Issue by bobchaos** [test-kitchen/kitchen-ec2#456]
Since this morning the default centos AMI search returns a Tableau image with a license. The expected behavior would be to receive an official Centos AMI. This can be countered with filters and/or static images but this self-updating behavior is handy in CI context as an early warning mechanism.

CentOS produces product codes for each major version, we could add a method that returns this product code for known versions, or falls back on the existing behavior for unhandled versions, minimizing the risk of fetching a "bad" image when using the default behavior.

relevant .kitchen.yml section that returns the Tableau AMI:
```
platforms:
  - name: centos-7
```

add this to make it work as intended:

```
platforms:
  - name: centos-7
    driver:
      image_search:
        product-code: aw0evgkw8e5c1q413zgy5pjce
        owner-alias: aws-marketplace
        name:
          - CentOS Linux 7*
          - CentOS-7*-GA-*
```
that is the default parameters plus the product code.

Software versions:
Test Kitchen version 1.23.2
chefdk 3.2.30
kitchen-ec2 (2.2.2)
