### ISSUE TITLE
Failed to complete #create action: [Must provide a positive integer for max_attempts profile option or for ENV['AWS_MAX_ATTEMPTS']]

### ISSUE THREAD

**Issue by lmayorga1980** [test-kitchen/kitchen-ec2#487]
**kitchen.yml**

```yaml
---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEYNAME'] %>
  region: us-east-1
  availability_zone: b
  instance_type: <%= ENV['AWS_INSTANCE_TYPE'] %>
  associate_public_ip: false
  interface: private
  subnet_id: <%= ENV['AWS_SUBNET_ID']  %>
  security_group_ids: <%= ENV['AWS_LINUX_SG_ID'] %>
  retryable_tries: 120
  shared_credentials_profile: saml
  user_data: user_data.sh

provisioner:
  name: shell
  script: 'bootstrap.sh'

verifier:
  name: inspec

transport:
    name: ssh
    ssl: true
    ssh_key: ~/.ssh/<%= ENV['AWS_SSH_KEYNAME'] %>.pem
    connect_timeout: 60
    connection_retries: 5
    username: centos

platforms:
  - name: centos-7
    driver:
      image_id: <%= ENV['AWS_LINUX_AMI_ID'] %>

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/os_spec
```

```

bundle exec kitchen converge
-----> Starting Test Kitchen (v2.4.0)
-----> Creating <default-centos-7>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Must provide a positive integer for max_attempts profile option or for ENV['AWS_MAX_ATTEMPTS']] on default-centos-7
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**gemset**
```
*** LOCAL GEMS ***

activesupport (5.2.4.2)
addressable (2.7.0)
aws-eventstream (1.0.3)
aws-partitions (1.293.0)
aws-sdk-apigateway (1.37.0)
aws-sdk-apigatewayv2 (1.18.0)
aws-sdk-athena (1.24.0)
aws-sdk-autoscaling (1.22.0)
aws-sdk-budgets (1.28.0)
aws-sdk-cloudformation (1.31.0)
aws-sdk-cloudhsm (1.20.0)
aws-sdk-cloudhsmv2 (1.21.0)
aws-sdk-cloudtrail (1.21.0)
aws-sdk-cloudwatch (1.34.0)
aws-sdk-cloudwatchlogs (1.29.0)
aws-sdk-codecommit (1.31.0)
aws-sdk-codedeploy (1.28.0)
aws-sdk-codepipeline (1.29.0)
aws-sdk-configservice (1.43.0)
aws-sdk-core (3.92.0)
aws-sdk-costandusagereportservice (1.19.0)
aws-sdk-dynamodb (1.45.0)
aws-sdk-ec2 (1.151.0)
aws-sdk-ecr (1.26.0)
aws-sdk-ecs (1.59.0)
aws-sdk-eks (1.35.0)
aws-sdk-elasticache (1.31.0)
aws-sdk-elasticbeanstalk (1.27.0)
aws-sdk-elasticloadbalancing (1.20.0)
aws-sdk-elasticloadbalancingv2 (1.41.0)
aws-sdk-elasticsearchservice (1.32.0)
aws-sdk-firehose (1.25.0)
aws-sdk-iam (1.34.0)
aws-sdk-kafka (1.19.0)
aws-sdk-kinesis (1.21.0)
aws-sdk-kms (1.30.0)
aws-sdk-lambda (1.38.0)
aws-sdk-organizations (1.17.0)
aws-sdk-rds (1.80.0)
aws-sdk-redshift (1.39.0)
aws-sdk-route53 (1.32.0)
aws-sdk-route53domains (1.19.0)
aws-sdk-route53resolver (1.12.0)
aws-sdk-s3 (1.61.1)
aws-sdk-securityhub (1.22.0)
aws-sdk-ses (1.28.0)
aws-sdk-sms (1.18.0)
aws-sdk-sns (1.22.0)
aws-sdk-sqs (1.24.0)
aws-sdk-ssm (1.73.0)
aws-sigv4 (1.1.1)
azure_graph_rbac (0.17.1)
azure_mgmt_key_vault (0.17.5)
azure_mgmt_resources (0.17.8)
azure_mgmt_security (0.18.0)
azure_mgmt_storage (0.20.0)
bcrypt_pbkdf (1.0.1)
bigdecimal (default: 1.4.1)
builder (3.2.4)
bundler (default: 1.17.3)
bundler-unload (1.0.2)
chef-config (15.8.23)
chef-telemetry (1.0.3)
chef-utils (15.8.23)
cmath (default: 1.0.0)
coderay (1.1.2)
concurrent-ruby (1.1.6)
csv (default: 3.0.9)
date (default: 2.0.0)
declarative (0.0.10)
declarative-option (0.1.0)
did_you_mean (1.3.0)
diff-lcs (1.3)
docker-api (1.34.2)
domain_name (0.5.20190701)
e2mmap (default: 0.1.0)
ecma-re-validator (0.2.0)
ed25519 (1.2.4)
equatable (0.6.1)
erubi (1.9.0)
etc (default: 1.0.1)
excon (0.73.0)
executable-hooks (1.6.0)
faraday (0.17.3)
faraday-cookie_jar (0.0.6)
faraday_middleware (0.12.2)
fcntl (default: 1.0.0)
ffi (1.12.2)
ffi-yajl (2.3.3)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
fuzzyurl (0.9.0)
gem-wrappers (1.4.0)
google-api-client (0.34.1)
googleauth (0.10.0)
gssapi (1.3.0)
gyoku (1.3.1)
hana (1.3.5)
hashie (3.6.0)
htmlentities (4.3.4)
http (2.2.2)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
httpclient (2.8.3)
i18n (1.8.2)
inifile (3.0.0)
inspec (4.18.100)
inspec-core (4.18.100)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
jmespath (1.4.0)
json (2.3.0, default: 2.1.0)
json_schemer (0.2.11)
jwt (2.2.1)
kitchen-ec2 (3.4.0)
kitchen-inspec (1.3.1)
libyajl2 (1.2.0)
license-acceptance (1.0.18)
little-plugger (1.1.4)
logger (default: 1.3.0)
logging (2.2.2)
matrix (default: 0.1.0)
memoist (0.16.2)
method_source (0.9.2)
mini_mime (1.0.2)
minitest (5.14.0, 5.11.3)
mixlib-config (3.0.6)
mixlib-install (3.12.1)
mixlib-log (3.0.8)
mixlib-shellout (3.0.9)
mixlib-versioning (1.2.12)
ms_rest (0.7.6)
ms_rest_azure (0.11.2)
multi_json (1.14.1)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
necromancer (0.5.1)
net-scp (2.0.0)
net-ssh (5.2.0)
net-ssh-gateway (2.0.0)
net-telnet (0.2.0)
nori (2.6.0)
openssl (default: 2.1.2)
os (1.1.0)
ostruct (default: 0.1.0)
parallel (1.19.1)
parslet (1.8.2)
pastel (0.7.3)
power_assert (1.1.3)
prime (default: 0.1.0)
pry (0.12.2)
psych (default: 3.1.0)
public_suffix (4.0.3)
rake (12.3.2)
rdoc (default: 6.1.0)
regexp_parser (1.7.0)
representable (3.0.4)
retriable (3.1.2)
retryable (3.0.5)
rexml (default: 3.1.9)
rspec (3.9.0)
rspec-core (3.9.1)
rspec-expectations (3.9.1)
rspec-its (1.3.0)
rspec-mocks (3.9.1)
rspec-support (3.9.2)
rss (default: 0.2.7)
rubygems-bundler (1.4.5)
rubyntlm (0.6.2)
rubyzip (1.3.0)
rvm (1.11.3.9)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
semverse (3.0.0)
shell (default: 0.7)
signet (0.13.2)
sslshake (1.3.0)
stringio (default: 0.0.2)
strings (0.1.8)
strings-ansi (0.2.0)
strscan (default: 1.0.0)
sync (default: 0.5.0)
term-ansicolor (1.7.1)
test-kitchen (2.4.0)
test-unit (3.2.9)
thor (0.20.3)
thread_safe (0.3.6)
thwait (default: 0.1.0)
timeliness (0.3.10)
tins (1.24.1)
tomlrb (1.3.0)
tracer (default: 0.1.0)
train (3.2.26)
train-aws (0.1.15)
train-core (3.2.26)
train-habitat (0.2.13)
train-winrm (0.2.6)
tty-box (0.5.0)
tty-color (0.5.1)
tty-cursor (0.7.1)
tty-prompt (0.21.0)
tty-reader (0.7.0)
tty-screen (0.7.1)
tty-table (0.11.0)
tzinfo (1.2.6)
uber (0.1.0)
unf (0.1.4)
unf_ext (0.0.7.2)
unicode-display_width (1.7.0)
unicode_utils (1.4.0)
uri_template (0.7.0)
webrick (default: 1.4.2)
winrm (2.3.4)
winrm-elevated (1.2.1)
winrm-fs (1.3.3)
wisper (2.0.1)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```
