### ISSUE TITLE
platform: rhel-7 search gets a beta ami

### ISSUE THREAD

**Issue by Stromweld** [test-kitchen/kitchen-ec2#505]
## :ghost: Brief Description

When using test-kitchen with ec2 driver I'm trying to get latest stable version of RHEL 7 image automatically. Instead of RHEL 7.8 I'm getting a RHEL 7.9 beta ami.

## Version

Chef Workstation version: 20.7.96
Chef Infra Client version: 16.2.73
Chef InSpec version: 4.21.3
Chef CLI version: 3.0.11
Test Kitchen version: 2.5.3
Cookstyle version: 6.12.6

Gem: kitchen-ec2 (3.7.1)

## Environment

Running kitchen command from aws windows workspaces machine. Running powershell and kitchen converge rhel-7.
snippet of my kitchen.ec2.yml file. Environment variable KITCHEN_LOCAL_YAML=kitchen.ec2.yml
```yaml
---
driver:
  name: ec2
  region: us-east-1
  subnet_id: subnet-example
  instance_type: t3a.medium
  retryable_tries: 120
platforms:
  - name: rhel-7
```

## Scenario

Converge on latest stable version of RHEL 7. Instead of getting a RHEL 7.8 machine I'm getting a RHEL 7.9 beta ami.

## Steps to Reproduce

create kitchen.yml with ec2 driver and platform name rhel-7 then run converge

## Expected Result

`cat /etc/redhat-release` to show that it's on a rhel 7.8 

## Actual Result

`cat /etc/redhat-release` will show that it's on a rhel 7.9 beta
