### ISSUE TITLE
block_duration_minutes option no longer working in the version > 3.7.0

### ISSUE THREAD

**Issue by ervinsh** [test-kitchen/kitchen-ec2#511]
## :ghost: Description

After adding hardcoded `instance_interruption_behavior:stop` option to spot request, `block_duration_minutes` option no longer working
https://github.com/test-kitchen/kitchen-ec2/blob/f8a310d5c55044e841d5b4daa16daded3de80aa0/lib/kitchen/driver/ec2.rb#L496

error message:
```
>>>>>>     Failed to complete #create action: [Could not create a spot instance:
The parameter BlockDurationMinutes cannot be specified when the instanceInterruptionBehavior is set to 'STOP'.] on default-centos-7
```

## Versions

test-kitchen (2.6.0)
kitchen-ec2 (3.7.1)

## Environment

kitchen.local.yml
```yaml
driver:
  name: ec2
  region: us-west-2
  instance_type: "t3.small"
  spot_price: '0.010'
  spot_wait: 600
  aws_ssh_key_id: <my-ssh-key>
  block_duration_minutes: 120
  shared_credentials_profile: <my_aws_profile>
  block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        volume_size: 16
        delete_on_termination: true


platforms:
  - name: centos-7
    transport:
      name: rsync
      username: centos
      ssh_key: ~/.ssh/<my-ssh-key>

  - name: amazon2
    transport:
      name: rsync
      username: ec2-user
      ssh_key: ~/.ssh/<my-ssh-key>
```

Please consider making `instance_interruption_behavior ` option configurable, or change to terminate in case block_duration_minutes option is set.
