### ISSUE TITLE
iam_profile_name not being added to ec2

### ISSUE THREAD

**Issue by aboutte** [test-kitchen/kitchen-ec2#54]
I am attempting to specify an AWS IAM role in my .kitchen.yml but when the EC2 instance is created the role it not attached to the instance which is being verified in the AWS console.  

test-kitchen (1.2.1)
kitchen-ec2 (0.8.0)

Here is my .kitchen.yml

```

---
driver:
  name: ec2
  aws_access_key_id: A....A
  aws_secret_access_key: S....v
  aws_ssh_key_id: s...s
  ssh_key: ~/.ssh/s....pem
  region: us-west-2
  availability_zone: us-west-2b
  require_chef_omnibus: true
  subnet_id: subnet-2...c 
  security_group_ids: ["sg-09...c", "sg-b...dd", "sg-...ad7", "sg-...46c"]
  iam_profile_name: chef-manager
  tags:
    Name: marketplace-test-kitchen
    created-by: test-kitchen

platforms:
  - name: AWS
    driver:
      image_id: ami-5....5
      username: ec2-user

suites:
  - name: default
    run_list:
      - role[base]
      - marketplace-shopatron
      - newrelic
    attributes:
```

What am I missing here?
