### ISSUE TITLE
Add ability to override block device mapping configurations for all devices

### ISSUE THREAD

**Issue by jakauppila** [test-kitchen/kitchen-ec2#585]
## :frowning_person: Problem Statement

To override configurations within `block_device_mappings` you need to call out each define and each configuration

https://kitchen.ci/docs/drivers/aws/#disk-configuration

It would be great if we could override (or provide defaults) for all devices with a single configuration.

## :grey_question: Possible Solution

I'm not sure the best way to combine the configuration in this case, do we need a new block that can provide defaults when building the object?

```
block_device_mappings_defaults:
    ebs:
      volume_type: gp3
      volume_size: 8
      delete_on_termination: true
```

## :heavy_plus_sign: Additional context

I'd be happy to implement this change if there's agreement on how to define the configuration.
