### ISSUE TITLE
Instance created but nothing happens from there

### ISSUE THREAD

**Issue by stormtrooperguy** [test-kitchen/kitchen-ec2#62]
I'm trying to move from kitchen-vagrant to kitchen-ec2. In my test cookbook I have the following .kitchen.yml

``` yaml

---
driver:
  name: ec2
  aws_access_key_id: "xxxxxx"
  aws_secret_access_key: "xxxxx"
  aws_ssh_key_id: "xxxxx"
  ssh_key: <%= File.expand_path('~/.ssh/xxxx.pem') %>
  region: "us-east-1"
  security_group_ids: ["sg-xxxx", "sg-xxxx", "sg-xxxx", "sg-xxxx", "sg-xxxx"]
  require_chef_omnibus: true
  iam_profile_name: "test-kitchen"
  require_chef_omnibus: true
provisioner:
  name: chef_solo
platforms:
  - name: centos-6.4
    driver:
      image_id: "ami-xxxxxx"
      username: "cloud-user"
suites:
  - name: default
    run_list:
      - recipe[system::default]
      - recipe[affect_utils::base_linux_users]
      - recipe[system::default]
      - recipe[system::nodejs]
      - recipe[system::rvm_user]
      - recipe[system::sunjava6]
      - recipe[system::tomcat6]
      - recipe[minitest-handler::default]

    attributes:
<%= File.read("./attributes.yaml") %>
```

When I run kitchen-test, I get:

``` text
[banderson@banderson system ]$ kitchen test default
-----> Starting Kitchen (v1.2.1)
-----> Cleaning up any prior instances of <default-centos-64>
-----> Destroying <default-centos-64>...
       Finished destroying <default-centos-64> (0m0.00s).
-----> Testing <default-centos-64>
-----> Creating <default-centos-64>...
[fog][WARNING] Unable to load the 'unf' gem. Your AWS strings may not be properly encoded.
       EC2 instance <i-7628515c> created.
.........................       (server ready)
```

And then it just sits. I left it for 15 minutes and there was no further progress (side note: I have installed unf, yet that message persists)

Any ideas what might be wrong? 

I've confirmed that the instance is created successfully, has the correct security groups, and can be connected to from the workstation that is running the kitchen test.
